-- AlterTable
ALTER TABLE "retro_items" ADD COLUMN     "fontColor" TEXT NOT NULL DEFAULT '#000000',
ADD COLUMN     "fontSize" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN     "posX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "posY" DOUBLE PRECISION NOT NULL DEFAULT 0;
